#!/bin/bash

# fetch_github_activity.sh
# Identifies recently active repositories and fetches contribution stats for weekly reports.

# Configuration
# Default to 7 days if no argument is provided
INPUT_RANGE=${1:-7}
DAYS=7

if [[ "$INPUT_RANGE" =~ ^([0-9]+)m$ ]]; then
    M_VAL="${BASH_REMATCH[1]}"
    DAYS=$(( M_VAL * 30 ))
elif [[ "$INPUT_RANGE" =~ ^([0-9]+)d$ ]]; then
    DAYS="${BASH_REMATCH[1]}"
elif [[ "$INPUT_RANGE" =~ ^[0-9]+$ ]]; then
    DAYS="$INPUT_RANGE"
else
    echo "Usage: $0 [number_of_days | number_of_months (e.g. 14, 14d, 1m)]"
    exit 1
fi

# Calculate approximate weeks needed (max 53)
WEEKS=$(( (DAYS / 7) + 2 ))
if [ $WEEKS -gt 53 ]; then WEEKS=53; fi

# Create output directory
OUTPUT_DIR="output"
mkdir -p "$OUTPUT_DIR"
OUTPUT_FILE="$OUTPUT_DIR/github_activity.md"

# Get the authenticated user's login
USERNAME=$(gh api user -q .login)

if [ -z "$USERNAME" ]; then
    echo "Error: Not authenticated with GitHub CLI. Please run 'gh auth login'."
    exit 1
fi

{
    echo "# GitHub Activity Summary ($(date +'%Y-%m-%d'))"
    echo "Range: Last $DAYS days"
    echo ""

    # 1. Recent Active Repositories
    echo "## Recently Active Repositories"
    gh repo list --limit 5 --sort updated --json name,updatedAt,description --template \
    '{{range .}}- **{{.name}}** (Updated: {{.updatedAt}})
  _{{.description}}_{{"\n"}}{{end}}'

    echo ""

    # 2. Recent Commits Across All Repositories
    echo "## Recent Commits (Last 10)"
    gh search commits --author "@me" --limit 10 --sort committer-date --json repository,sha,commit --template \
    '{{range .}}- **[{{.repository.name}}]** {{.commit.message}} ({{.commit.committer.date}}){{"\n"}}{{end}}'

    echo ""

    # 3. Overall Contributions (Heatmap Data)
    echo "## Contribution Stats"
    # Fetch total and daily contributions using GraphQL
    DATA=$(gh api graphql -f query='
  query($userName:String!) {
    user(login: $userName) {
      contributionsCollection {
        contributionCalendar {
          totalContributions
          weeks {
            contributionDays {
              contributionCount
              date
            }
          }
        }
      }
    }
  }
' -f userName="$USERNAME")

    TOTAL_CONTRIBUTIONS=$(echo "$DATA" | jq -r '.data.user.contributionsCollection.contributionCalendar.totalContributions')

    if [ -n "$TOTAL_CONTRIBUTIONS" ] && [ "$TOTAL_CONTRIBUTIONS" != "null" ]; then
        echo "Total contributions (Last 365 days): **$TOTAL_CONTRIBUTIONS**"
        echo ""
        echo "### Daily Activity (Last $DAYS Days)"
        echo "$DATA" | jq -r --argjson days "$DAYS" --argjson weeks "$WEEKS" \
            '.data.user.contributionsCollection.contributionCalendar.weeks[-$weeks:] | map(.contributionDays[]) | .[-$days:] | .[] | "- \(.date): **\(.contributionCount)** contributions"'
    else
        echo "Could not fetch contribution stats."
    fi

    echo ""
    echo "---"
    echo "_Generated by fetch_github_activity.sh_"
} > "$OUTPUT_FILE"

echo "✅ GitHub activity report has been saved to: $OUTPUT_FILE"
